### PR TITLE
Install chrome on travis

### PR DESCRIPTION
**Pull request by 810**

### CODE REVIEW

**Comment by 810** [comment]
Ok, here is the summury:

1) Chrome works only on the new ubuntu 14.0.4, not on 12.0.4
2) When enable `dist: trust` other checks are failing like apc
3) Also we have a issue with the install Acceptance:
````
12:31:54.530 SEVERE - http://localhost/tests/codeception/joomla-cms3/installation/index.php - Failed to load resource: the server responded with a status of 404 (Not Found)

1437  12:31:54.615 SEVERE - http://localhost/favicon.ico - Failed to load resource: the server responded with a status of 404 (Not Found)

````

We can't use older chrome versions or chromium because the webdriver doesn't support them

**Comment by yvesh** [comment]
@810 Hmm looks like the files are not in the document root of the webserver or the copy failed.. Can you do a ls -al and then check ls -al tests/codeption/joomla-cms3 ? If this is right it's maybe an apache config issue..

Thank you!

**Comment by 810** [comment]
The dir is there.

**Comment by yvesh** [comment]
Probably a Apache issue then.. We need to check and test the config :(

**Comment by 810** [comment]
Closing this one for a new pr.

**Pull request closed without merging**
