### PR TITLE
Integration of system tests for Joomla! with codeception 2.2

### PR DESCRIPTION
**Pull request by yvesh**
Basic integration of codeception 2.2RC, including full travis support. Current joomla php unit tests are run from tests-phpunit folder. New system tests are run after them.

[Travis success log](https://travis-ci.org/yvesh/gsoc16_browser-automated-tests/builds/127202021)
#### Summary of Changes
- Update Composer 
- Integration of CodeCeption 2.2RC
- Added Robo.li taskrunner and configuration
- One sample test for com_users (create user)
- Adjusted travis to run system tests and unit tests
### Preparations

`composer install`

Copy RoboFile.dist.ini to RoboFile.ini and adjust it to your needs
`cp RoboFile.dist.ini RoboFile.ini`

Copy tests/acceptance.suite.dist.yml to tests/acceptance.suite.yml and adjust it
`cp tests/acceptance.suite.dist.yml tests/acceptance.suite.yml`
### Run tests with:

`libraries/vendor/bin/robo run:tests`
### Run a single test:

`libraries/vendor/bin/robo run:test`

### CODE REVIEW

**Comment by nibra** [comment]
Looks good to me.

**Comment by javigomez** [comment]
I have closed an opened to launch travis. I have activated Travis in the repo.

**Comment by javigomez** [comment]
Tested. Works:

screen shot 2016-05-02 at 20 11 06

There is also an alternative possibility that we can take in consideration @yvesh, @nibra, @pritalpatel.

Instead of adding all the Libraries required for running Codeception tests in the root of joomla, we clould also have a composer just for the tests: https://github.com/joomla/joomla-cms/blob/staging/tests/codeception/composer.json

That way we don't need to affect Joomla for running the tests at all.

**Comment by nibra** [comment]
@javigomez The vendor folder does not belong to the repo. In the Pythagoras repo, we have already removed it (for the 3.x branches), but we're waiting for Robert Deutz to adapt the packager (as the files still need to be part of the distributable) before we can move that over to the CMS. Beyond that, the test related dependencies are listed under 'require-dev', so everything is fine. No need for extra complexity.

**Pull request merged**
